// src/db/model/userModel.ts

export interface User {
    user_id?: number;          // Optional, as it's typically auto-generated by the database
    fname: string;
    lname: string;
    email: string;
    password: string;
    role: string;
    citizen_id?: string;       // Optional if nullable in the database
    phone_number?: string;     // Optional if nullable in the database
    address_line1?: string;    // Optional if nullable in the database
    city?: string;
    state?: string;
    postal_code?: string;
    country?: string;
    company_id?: number;       // Optional if nullable in the database
    profile_picture_url?: string;  // New field for profile picture URL

}
